spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: kjyoui77
    driver-class-name: com.mysql.cj.jdbc.Driver